### ISSUE TITLE
HO event crash srsENB.

### ISSUE THREAD

**Issue by cbalint13** [srsran/srsRAN#718]
### Issue Description
A specific HO event from S1AP crash srsENB.
   1. A test COTS-UE registered to vendor-eNB.
   2. srsENB comes on-air (with much higher power than adjacent)
   3. srsENB<->EPC(vendor) **HandoverRequest** for COTS-UE crashes srsENB.

### Setup Details
  - latest srsRAN git-head
  - COTS-UE <-> limeSDR <-> srsENB <-> S1AP/EPC(vendor)

### Expected Behavior
- HO requests should not crash srsENB.

### Additional Information
Please see attached [ho-crash.tar.gz](https://github.com/srsran/srsRAN/files/7079498/ho-crash.tar.gz) having:
   - srsENB logs (debug level)
   - s1ap / enb pcap (srsENB dumps)
   - crash trace back (srsENB provided)
   - full gdb text backtrace (from coredump)

Summary backtrace from gdb :
```
(gdb) bt
#0  0x0000000000562084 in srsenb::apply_rr_cfg_ded_diff (current_rr_cfg_ded=..., pending_rr_cfg_ded=...) at /home/cbalint/rpmbuild/BUILD/srsRAN/srsenb/src/stack/rrc/ue_rr_cfg.cc:386
#1  0x000000000052ccce in srsenb::rrc::ue::rrc_mobility::apply_ho_prep_cfg (this=<optimized out>, ho_prep=..., ho_req_msg=..., erabs_failed_to_setup=..., cause=...)
    at /home/cbalint/rpmbuild/BUILD/srsRAN/srsenb/src/stack/rrc/rrc_mobility.cc:963
#2  0x0000000000535aff in srsenb::rrc::ue::rrc_mobility::handle_ho_requested (this=0x7f5e82d913c0, s=..., ho_req=...) at /home/cbalint/rpmbuild/BUILD/srsRAN/srsenb/src/stack/rrc/rrc_mobility.cc:746
#3  0x000000000054a9a1 in srsran::base_fsm_t<srsenb::rrc::ue::rrc_mobility>::row<srsenb::rrc::ue::rrc_mobility::idle_st, srsenb::rrc::ue::rrc_mobility::s1_target_ho_st, srsenb::rrc::ue::rrc_mobility::ho_req_rx_ev, &srsenb::rrc::ue::rrc_mobility::handle_ho_requested, (bool (srsenb::rrc::ue::rrc_mobility::*)(srsenb::rrc::ue::rrc_mobility::idle_st&, srsenb::rrc::ue::rrc_mobility::ho_req_rx_ev const&))0>::react (ev=..., s=..., f=0x7f5e82d913c0)
```
FullFrame (pretty-print) version of backtrace is in the archive.

Thank you !

**Comment by andrepuschmann** [comment]
Thanks for reporting this @cbalint13 ! We'll look into it.
